#kubectl create -f Cronjobdemo.yaml
# kubectl get all < To see the jobs create and pod>
#kubectl logs <pod>
#kubectl describe cronjob helloworld-cron | less
# kubectl delete cronjob helloworld-cron
apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello Kubernetes!!!"]
          restartPolicy: Never