# Backoff limit
#kubectl apply -f jobdemo5.yaml
# kubectl get all < To see the jobs create and pod>
# kubectl describe job helloworld | less   # Run it after 5 min 
# kubectl delete job helloworld 
# EVENN IF WE DELETE JOB BEFORE 60 SEC POD WILL CREATE AGAIN 
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["ls", "/bipeen"] # Since there is no directlry name bipeen in Busybox container with  Fail and exit with status 0
      restartPolicy: Never