#kubectl apply -f jobdemo.yaml
# kubectl get all < To see the jobs create and pod>
#kubectl logs <pod>
#kubectl describe job helloworld | less
# kubectl delete job helloworld
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Hello Kubernetes!!!"]
      restartPolicy: Never